from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("peluquerias/<slug:slug>/", views.salon_detail, name="salon-detail"),
    path("peluquerias/<slug:slug>/configuracion/", views.salon_settings, name="salon-settings"),
    path("peluquerias/<slug:slug>/equipo/", include("salons.team_urls")),
    path("peluquerias/<slug:slug>/sucursales/", views.branch_management, name="branch-management"),
    path("peluquerias/<slug:slug>/sucursales/<int:pk>/editar/", views.branch_management, name="branch-edit"),
    path("peluquerias/<slug:slug>/servicios/", views.service_management, name="service-management"),
    path("peluquerias/<slug:slug>/servicios/<int:pk>/editar/", views.service_edit, name="service-edit"),
    path("peluquerias/<slug:slug>/servicios-por-sucursal/<int:pk>/editar/", views.offering_edit, name="offering-edit"),
    path("peluquerias/<slug:slug>/profesionales/", views.professional_management, name="professional-management"),
    path("peluquerias/<slug:slug>/profesionales/<int:pk>/editar/", views.professional_management, name="professional-edit"),
    path("peluquerias/<slug:slug>/excepciones/", views.booking_limit_exceptions, name="booking-limit-exceptions"),
    path("peluquerias/<slug:slug>/recompensas/", views.reward_settings, name="reward-settings"),
    path("peluquerias/<slug:slug>/disponibilidad/", views.availability_settings, name="availability-settings"),
    path("peluquerias/<slug:slug>/disponibilidad/<str:kind>/<int:pk>/eliminar/", views.availability_delete, name="availability-delete"),
    path("agenda/", views.agenda, name="agenda"),
    path("agenda/reservas/<int:pk>/estado/", views.reservation_status, name="reservation-status"),
    path("agenda/reservas/<int:pk>/reprogramar/", views.reservation_reschedule, name="reservation-reschedule"),
    path("agenda/reservas/<int:pk>/reprogramar/horarios/", views.reservation_reschedule_slots, name="reservation-reschedule-slots"),
    path("reservar/<slug:slug>/", views.public_salon, name="public-salon"),
    path("reservar/<slug:slug>/invitado/", views.guest_start, name="guest-start"),
    path("reservar/<slug:slug>/salir/", views.guest_logout, name="guest-logout"),
    path("reservar/<slug:slug>/verificar/", views.guest_verify, name="guest-verify"),
    path("reservar/<slug:slug>/turno/", views.booking_create, name="booking-create"),
    path("reservar/<slug:slug>/mis-reservas/", views.my_reservations, name="my-reservations"),
    path("reservar/<slug:slug>/horarios/", views.booking_slots, name="booking-slots"),
    path("reservar/<slug:slug>/confirmada/", views.booking_success, name="booking-success"),
    path("reservar/<slug:slug>/cancelar/<uuid:token>/", views.client_cancel, name="client-cancel"),
    path("reservar/<slug:slug>/reprogramar/<uuid:token>/", views.client_reschedule, name="client-reschedule"),
    path("reservar/<slug:slug>/reprogramar/<uuid:token>/horarios/", views.client_reschedule_slots, name="client-reschedule-slots"),
]
