# Generated by Django 5.2.7 on 2026-10-03 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HairSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'peluquería',
                'verbose_name_plural': 'peluquerías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('address', models.CharField(max_length=250, verbose_name='dirección')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='salons.hairsalon', verbose_name='peluquería')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrador'), ('hairdresser', 'Peluquero')], max_length=20, verbose_name='rol')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='salons.hairsalon', verbose_name='peluquería')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
            },
        ),
        migrations.CreateModel(
            name='MembershipBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.branch')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.membership')),
            ],
            options={
                'verbose_name': 'acceso a sucursal',
                'verbose_name_plural': 'accesos a sucursales',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='authorized_memberships', through='salons.MembershipBranch', to='salons.branch'),
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=160, verbose_name='nombre visible')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='salons.hairsalon', verbose_name='peluquería')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.branch')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.professional')),
            ],
            options={
                'verbose_name': 'asignación de profesional a sucursal',
                'verbose_name_plural': 'asignaciones de profesionales a sucursales',
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='professionals', through='salons.ProfessionalBranch', to='salons.branch'),
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.professional')),
            ],
            options={
                'verbose_name': 'servicio de profesional',
                'verbose_name_plural': 'servicios de profesionales',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('professionals', models.ManyToManyField(blank=True, related_name='services', through='salons.ProfessionalService', to='salons.professional')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.hairsalon', verbose_name='peluquería')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.service'),
        ),
        migrations.CreateModel(
            name='BranchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='duración (minutos)')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='salons.branch', verbose_name='sucursal')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_offerings', to='salons.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'servicio por sucursal',
                'verbose_name_plural': 'servicios por sucursal',
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('salon', 'name'), name='unique_branch_name_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='membershipbranch',
            constraint=models.UniqueConstraint(fields=('membership', 'branch'), name='unique_membership_branch'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('salon', 'user'), name='unique_membership_per_salon_user'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('salon',), name='one_owner_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='professionalbranch',
            constraint=models.UniqueConstraint(fields=('professional', 'branch'), name='unique_professional_branch'),
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(fields=('salon', 'display_name'), name='unique_professional_name_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('salon', 'user'), name='unique_professional_user_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('salon', 'name'), name='unique_service_name_per_salon'),
        ),
        migrations.AddConstraint(
            model_name='professionalservice',
            constraint=models.UniqueConstraint(fields=('professional', 'service'), name='unique_professional_service'),
        ),
        migrations.AddConstraint(
            model_name='branchservice',
            constraint=models.UniqueConstraint(fields=('branch', 'service'), name='unique_service_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='branchservice',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5)), name='service_duration_at_least_5_minutes'),
        ),
    ]
