# Generated by Django 5.2.7 on 2026-10-03 18:57

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='GuestVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='correo electrónico')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(verbose_name='vence')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'verificación de invitado',
                'verbose_name_plural': 'verificaciones de invitados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día')),
                ('starts_at', models.TimeField(verbose_name='inicio')),
                ('ends_at', models.TimeField(verbose_name='fin')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='salons.branch', verbose_name='sucursal')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='salons.professional', verbose_name='profesional')),
            ],
            options={
                'verbose_name': 'jornada profesional',
                'verbose_name_plural': 'jornadas profesionales',
                'ordering': ['weekday', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.TimeField(verbose_name='inicio')),
                ('ends_at', models.TimeField(verbose_name='fin')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='salons.workschedule', verbose_name='jornada')),
            ],
            options={
                'verbose_name': 'descanso',
                'verbose_name_plural': 'descansos',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('reason', models.CharField(blank=True, max_length=180, verbose_name='motivo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_absences', to='salons.branch', verbose_name='sucursal')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='salons.professional', verbose_name='profesional')),
            ],
            options={
                'verbose_name': 'ausencia profesional',
                'verbose_name_plural': 'ausencias profesionales',
                'ordering': ['starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='absence_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('contact', models.CharField(max_length=100, verbose_name='contacto')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('occupied_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='intervalo ocupado')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='duración guardada')),
                ('cancellation_notice_hours', models.PositiveSmallIntegerField(default=24, verbose_name='anticipación para cancelar')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida')], default='confirmed', max_length=24, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='salons.branch', verbose_name='sucursal')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='salons.professional', verbose_name='profesional')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='salons.hairsalon', verbose_name='peluquería')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='salons.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='reservation_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'confirmed')), expressions=[('professional', '='), ('occupied_range', '&&')], name='prevent_professional_reservation_overlap')],
            },
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('professional', 'branch', 'weekday', 'starts_at'), name='unique_work_schedule_start'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='work_schedule_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='schedulebreak',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='schedule_break_end_after_start'),
        ),
    ]
