# Generated by Django 5.2.7 on 2026-10-03 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_cancellation_policy_and_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLimitException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='correo del cliente')),
                ('booking_date', models.DateField(verbose_name='fecha de las reservas')),
                ('reason', models.CharField(max_length=300, verbose_name='motivo')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_booking_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='autorizada por')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limit_exception', to='salons.reservation', verbose_name='reserva que utilizó la excepción')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_limit_exceptions', to='salons.hairsalon', verbose_name='peluquería')),
            ],
            options={
                'verbose_name': 'excepción al límite de reservas',
                'verbose_name_plural': 'excepciones al límite de reservas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['salon', 'customer_email', 'booking_date', 'used_at'], name='booking_exception_lookup')],
            },
        ),
    ]
