# Generated by Django 5.2.7 on 2026-10-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_bookinglimitexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reward_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='descuento de recompensa'),
        ),
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='activo')),
                ('services_required', models.PositiveSmallIntegerField(default=5, verbose_name='servicios atendidos requeridos')),
                ('period', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=12, verbose_name='período')),
                ('discount_percent', models.PositiveSmallIntegerField(default=10, verbose_name='porcentaje de descuento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_program', to='salons.hairsalon', verbose_name='peluquería')),
            ],
            options={
                'verbose_name': 'programa de recompensas',
                'verbose_name_plural': 'programas de recompensas',
                'constraints': [models.CheckConstraint(condition=models.Q(('services_required__gte', 1)), name='reward_services_at_least_one'), models.CheckConstraint(condition=models.Q(('discount_percent__gte', 1), ('discount_percent__lte', 100)), name='reward_discount_valid_percent')],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='correo del cliente')),
                ('period_start', models.DateField(verbose_name='inicio del período')),
                ('period_end', models.DateField(verbose_name='fin del período')),
                ('attended_services', models.PositiveSmallIntegerField(verbose_name='servicios atendidos')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='porcentaje canjeado')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reward_redemption', to='salons.reservation', verbose_name='reserva del canje')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='salons.hairsalon', verbose_name='peluquería')),
            ],
            options={
                'verbose_name': 'canje de recompensa',
                'verbose_name_plural': 'canjes de recompensas',
                'ordering': ['-redeemed_at'],
                'constraints': [models.UniqueConstraint(fields=('salon', 'customer_email', 'period_start'), name='one_reward_redemption_per_period')],
            },
        ),
    ]
