# Generated by Django 5.2.7 on 2026-10-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_reservation_reward_discount_percent_rewardprogram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_starts_at', models.DateTimeField(verbose_name='inicio anterior')),
                ('previous_ends_at', models.DateTimeField(verbose_name='fin anterior')),
                ('new_starts_at', models.DateTimeField(verbose_name='inicio nuevo')),
                ('new_ends_at', models.DateTimeField(verbose_name='fin nuevo')),
                ('source', models.CharField(choices=[('client', 'Cliente'), ('salon', 'Peluquería')], max_length=12, verbose_name='origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_reschedules', to=settings.AUTH_USER_MODEL, verbose_name='modificada por')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='salons.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'reprogramación',
                'verbose_name_plural': 'reprogramaciones',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('previous_ends_at__gt', models.F('previous_starts_at'))), name='reschedule_previous_end_after_start'), models.CheckConstraint(condition=models.Q(('new_ends_at__gt', models.F('new_starts_at'))), name='reschedule_new_end_after_start')],
            },
        ),
    ]
