# Generated by Django 5.2.7 on 2026-10-05 01:15

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_reservation_cancelled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida'), ('in_progress', 'En curso'), ('no_show', 'Ausente')], max_length=24)),
                ('new_status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida'), ('in_progress', 'En curso'), ('no_show', 'Ausente')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='prevent_professional_reservation_overlap',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida'), ('in_progress', 'En curso'), ('no_show', 'Ausente')], default='confirmed', max_length=24, verbose_name='estado'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['confirmed', 'in_progress'])), expressions=[('professional', '='), ('occupied_range', '&&')], name='prevent_professional_reservation_overlap'),
        ),
        migrations.AddField(
            model_name='reservationstatuschange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationstatuschange',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='salons.reservation'),
        ),
    ]
