# Generated by Django 5.2.7 on 2026-10-05 01:38

import django.contrib.postgres.constraints
from django.db import migrations, models


def restore_confirmed(apps, schema_editor):
    Reservation = apps.get_model('salons', 'Reservation')
    History = apps.get_model('salons', 'ReservationStatusChange')
    alias = schema_editor.connection.alias
    # Keep the old exclusion constraint while converting: both values occupy
    # the same interval, so no conflicting turn can be introduced.
    while True:
        ids = list(Reservation.objects.using(alias).select_for_update().filter(status='in_progress').order_by('pk').values_list('pk', flat=True)[:500])
        if not ids:
            break
        History.objects.using(alias).bulk_create([
            History(reservation_id=pk, previous_status='in_progress', new_status='confirmed', changed_by_id=None)
            for pk in ids
        ])
        Reservation.objects.using(alias).filter(pk__in=ids).update(status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_reservationstatuschange_and_more'),
    ]

    operations = [
        migrations.RunPython(restore_confirmed, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='prevent_professional_reservation_overlap',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida'), ('no_show', 'Ausente')], default='confirmed', max_length=24, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reservationstatuschange',
            name='new_status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida'), ('no_show', 'Ausente')], max_length=24),
        ),
        migrations.AlterField(
            model_name='reservationstatuschange',
            name='previous_status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled_client', 'Cancelada por cliente'), ('cancelled_salon', 'Cancelada por local'), ('completed', 'Atendida'), ('no_show', 'Ausente')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'confirmed')), expressions=[('professional', '='), ('occupied_range', '&&')], name='prevent_professional_reservation_overlap'),
        ),
    ]
