# Generated by Django 5.2.7 on 2026-10-07 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0009_simplify_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsalon',
            name='cancellation_block_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='duración del bloqueo (horas)'),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='cancellation_block_threshold',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='cancelaciones que activan el bloqueo'),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='cancellation_block_window_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='ventana de cancelaciones (días)'),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='max_booking_horizon_days',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='horizonte máximo de reserva (días)'),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='max_daily_bookings_per_client',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='reservas activas por cliente y día'),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='min_booking_notice_minutes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10080)], verbose_name='anticipación mínima para reservar (minutos)'),
        ),
        migrations.AddField(
            model_name='hairsalon',
            name='slot_interval_minutes',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Cada 5 minutos'), (10, 'Cada 10 minutos'), (15, 'Cada 15 minutos'), (20, 'Cada 20 minutos'), (30, 'Cada 30 minutos'), (60, 'Cada 60 minutos')], default=15, verbose_name='intervalo entre inicios de turno'),
        ),
        migrations.AddConstraint(
            model_name='hairsalon',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_block_hours__gte', 1), ('cancellation_block_hours__lte', 720), ('cancellation_block_threshold__gte', 1), ('cancellation_block_threshold__lte', 20), ('cancellation_block_window_days__gte', 1), ('cancellation_block_window_days__lte', 365), ('max_booking_horizon_days__gte', 1), ('max_booking_horizon_days__lte', 365), ('max_daily_bookings_per_client__gte', 1), ('max_daily_bookings_per_client__lte', 50), ('min_booking_notice_minutes__lte', 10080), ('slot_interval_minutes__in', [5, 10, 15, 20, 30, 60])), name='salon_operational_policies_valid'),
        ),
    ]
